### PR TITLE
Add dashboard redirect for authed users

### PR DESCRIPTION
**Pull request by cholladay0816**
Solves #6 by adding a check for an existing session, and if one exists, redirecting to the homepage.

### CODE REVIEW

**Comment by Nickatak** [comment]
Hello Chris! Sorry for the delayed response (I was busy throughout this evening).  Welcome to the project, and thank you for taking the time to tweak your commits for flake8.   ~~Do you mind squashing your commits down to one commit?~~

Edit: I can commit and squash them when I merge.  This definitely needs a test case added for it though (I think under `/tests/auth/test_login_view.py` in the `TestRouteBehavior` Test-class).

**Comment by Nickatak** [comment]
Also, this needs a test case written for it.

**Review by Nickatak — APPROVED** [review]

**Comment by cholladay0816** [comment]
Thanks for taking the time to reply and provide feedback, I'd love to help out in any way I can and I'll be sure to add the test case when I'm available!

**Comment by Nickatak** [comment]
Absolutely! Please let me know if you need help with anything/want to tackle an issue on your own (as you can see, the app's only about halfway built right now, so there's quite a few things left to do).  Once you've submitted a test for this, I'll accept the PR and merge it C:

**Review by Nickatak — CHANGES_REQUESTED** [review]
Line 151: `location = client.get(...)` needs to remove the variable assignment (unused).

There also needs to be another newline @ line 153 (two newlines total after the end of a method, and beginning of a new class, between line 152 [`assert headers['Location']....`] and line 154 [`class TestFormValidation...`]).

Edit: brackets*

**Comment by cholladay0816** [comment]
Sorry about that, the first commit was a bit early and I meant to mark it as a draft sooner.  PyTest and Flake8 are pretty new to me but it was a lot of fun to learn and get everything working, thanks for helping me figure everything out!

**Comment by Nickatak** [comment]
No problems.  This project is meant for learning (for everyone)!  Thanks for contributing, and if you'd like to work on anything, feel free to open up your own issue as this thing is currently under development.  Also, just a heads up, I sent you an email (to your listed email on your profile site).

**Pull request merged**
